### ISSUE TITLE
Kick and error on give Item(Advanced creative tab)

### ISSUE THREAD

**Issue by Neewen** [dodofan/Taka#16]
**Issue:**

Kick and error on give Item(Advanced creative tab)

The error:

> [18:45:50 INFO]: Gaaxb lost connection: 
> [18:45:50 INFO]: - >> Joueur Gaaxb
> [18:45:50 WARN]: java.lang.NullPointerException
> [18:45:50 WARN]:        at TAKA.R.a(R.java)
> [18:45:50 WARN]:        at TAKA.aT.a(aT.java)
> [18:45:50 WARN]:        at TAKA.R.a(R.java)
> [18:45:50 WARN]:        at TAKA.Taka.a(Taka.java)
> [18:45:50 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor278.execute(Unknown Source)
> [18:45:50 WARN]:        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
> [18:45:50 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
> [18:45:50 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [18:45:50 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
> [18:45:50 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
> [18:45:50 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:608)
> [18:45:50 WARN]:        at net.minecraft.server.v1_9_R2.PacketPlayInFlying.a(SourceFile:126)
> [18:45:50 WARN]:        at net.minecraft.server.v1_9_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57)
> [18:45:50 WARN]:        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
> [18:45:50 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [18:45:50 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [18:45:50 WARN]:        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
> [18:45:50 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786)
> [18:45:50 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403)
> [18:45:50 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723)
> [18:45:50 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622)
> [18:45:50 WARN]:        at java.lang.Thread.run(Thread.java:748)
> [18:45:50 WARN]: handleDisconnection() called twice
> 

**Reproduction method (steps to reproduce the issue):**

In the video

**Screenshots or videos (if applicable):**

https://youtu.be/Xi14Z-WQR0M

**Plugin version and applicable configuration settings:**

![image](https://user-images.githubusercontent.com/62424178/78052957-23b08300-7380-11ea-8a4b-386c29051527.png)

![image](https://user-images.githubusercontent.com/62424178/78052990-34f98f80-7380-11ea-9de5-87b6cd3ab9c9.png)

**Comment by dani02021** [comment]
Thank you for the report. Will be fixed in the next update!
