### ISSUE TITLE
Error on BlockBreakEvent on PaperSpigot 1.9.4

### ISSUE THREAD

**Issue by Neewen** [dodofan/Taka#3]
**When I break a block I make this error, is it possible to fix it ? please** (I forgot to say I'm using TakaAntiCheat 6.1.6.)

The Error:

> [23:57:17 ERROR]: Could not pass event BlockBreakEvent to TakaAntiCheat v6.1.6
> java.lang.NoSuchFieldError: BEETROOTS
>         at TAKA.G.a(G.java) ~[?:?]
>         at TAKA.Y.a(Y.java) ~[?:?]
>         at TAKA.G.a(G.java) ~[?:?]
>         at TAKA.Taka.a(Taka.java) ~[?:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor437.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.4.jar:git-Paper-773]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.4.jar:git-Paper-773]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.4.jar:git-Paper-773]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.4.jar:git-Paper-773]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:293) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.PlayerInteractManager.a(PlayerInteractManager.java:125) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:832) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.PacketPlayInBlockDig.a(SourceFile:40) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.PacketPlayInBlockDig.a(SourceFile:10) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-773]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
>         at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-773]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
> [23:57:17 WARN]: [TakaAntiCheat] Task #188 for TakaAntiCheat v6.1.6 generated an exception
> java.lang.NoSuchFieldError: BEETROOTS
>         at TAKA.G.a(G.java) ~[?:?]
>         at TAKA.R.a(R.java) ~[?:?]
>         at TAKA.G.a(G.java) ~[?:?]
>         at TAKA.be.run(be.java) ~[?:?]
>         at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.9.4.jar:git-Paper-773]
>         at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:795) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-773]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by Neewen** [comment]
I forgot to say I'm using TakaAntiCheat 6.1.6.

**Comment by dani02021** [comment]
Thank you for the report, fixed, the update will be posted after a few hours.
