### ISSUE TITLE
Levitation Effect Alert for Fly on PaperSpigot 1.9.4

### ISSUE THREAD

**Issue by Neewen** [dodofan/Taka#4]
**Issue:**

That tells me that the hack person for fly is at the end of the effect. 

**Reproduction method (steps to reproduce the issue):**

I did "/effect %player% minecraft:levitation 1 2" and at the end of the time it detected a Fly

**Screenshots or videos (if applicable):**

![Pactify_pE0mklv7nD](https://user-images.githubusercontent.com/62424178/77155987-b9a1ff00-6a9e-11ea-9047-8399657222bf.png)

**Plugin version and applicable configuration settings:**
version server:
![image](https://user-images.githubusercontent.com/62424178/77156030-d0e0ec80-6a9e-11ea-97a4-944cd320830c.png)

version TakaAntiCheat:
![image](https://user-images.githubusercontent.com/62424178/77156077-ec4bf780-6a9e-11ea-8634-02737778b723.png)

**Comment by dani02021** [comment]
Fixed
