### ISSUE TITLE
Error when typing a mobs (EntityDamageByEntityEvent) on PaperSpigot 1.9.4 

### ISSUE THREAD

**Issue by Neewen** [dodofan/Taka#5]
**Issue:**

The error:
> [11:38:45 ERROR]: Could not pass event EntityDamageByEntityEvent to TakaAntiCheat v6.1.6
> java.lang.NoSuchFieldError: ENTITY_SWEEP_ATTACK
>         at TAKA.V.a(V.java) ~[?:?]
>         at TAKA.G.a(G.java) ~[?:?]
>         at TAKA.Taka.a(Taka.java) ~[?:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor431.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.4.jar:git-Paper-773]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.4.jar:git-Paper-773]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.4.jar:git-Paper-773]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.4.jar:git-Paper-773]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.4.jar:git-Paper-773]
>         at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [patched_1.9.4.jar:git-Paper-773]
>         at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:570) [patched_1.9.4.jar:git-Paper-773]
>         at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [patched_1.9.4.jar:git-Paper-773]
>         at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:602) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.EntityLiving.damageEntity0(EntityLiving.java:1236) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.EntityLiving.damageEntity(EntityLiving.java:835) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.EntityMonster.damageEntity(EntityMonster.java:44) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.EntityZombie.damageEntity(EntityZombie.java:180) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.EntityHuman.attack(EntityHuman.java:1022) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.EntityPlayer.attack(EntityPlayer.java:1169) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1614) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:48) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:5) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-773]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
>         at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-773]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Reproduction method (steps to reproduce the issue):**

Hit a zombie (does it on any mob).

**Screenshots or videos (if applicable):**

![image](https://user-images.githubusercontent.com/62424178/77156661-0f2adb80-6aa0-11ea-8d06-1078e94c6b9c.png)

**Plugin version and applicable configuration settings:**

Server version:
![Pactify_y9A8KJc4v3](https://user-images.githubusercontent.com/62424178/77156399-96c41a80-6a9f-11ea-9c6e-2a33121ab27b.png)

TakaAntiCheat version:
![Pactify_Qei8oNp6Os](https://user-images.githubusercontent.com/62424178/77156405-9a57a180-6a9f-11ea-8573-c9445453d4aa.png)

**Comment by dani02021** [comment]
Thank you for the report, fixed, an update will be posted after a few hours!
Have a nice day!
