### ISSUE TITLE
Error on BlockPlaceEvent on PaperSpigot 1.9.4 

### ISSUE THREAD

**Issue by Neewen** [dodofan/Taka#6]
**Issue:**

The error:

> [11:48:47 ERROR]: Could not pass event BlockPlaceEvent to TakaAntiCheat v6.1.6
> java.lang.NoSuchFieldError: BEETROOTS
>         at TAKA.G.a(G.java) ~[?:?]
>         at TAKA.Y.a(Y.java) ~[?:?]
>         at TAKA.G.a(G.java) ~[?:?]
>         at TAKA.Taka.a(Taka.java) ~[?:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor421.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.4.jar:git-Paper-773]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.4.jar:git-Paper-773]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.4.jar:git-Paper-773]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.4.jar:git-Paper-773]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.4.jar:git-Paper-773]
>         at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:146) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.ItemStack.placeItem(ItemStack.java:166) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.PlayerInteractManager.a(PlayerInteractManager.java:523) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:888) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.PacketPlayInUseItem.a(SourceFile:55) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.PacketPlayInUseItem.a(SourceFile:11) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-773]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
>         at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-773]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-773]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Reproduction method (steps to reproduce the issue):**

Gaaxb placed a block 

**Screenshots or videos (if applicable):**

![image](https://user-images.githubusercontent.com/62424178/77156998-ce7f9200-6aa0-11ea-8cfa-5a6cebd5349a.png)

**Plugin version and applicable configuration settings:**
version server:
![image](https://user-images.githubusercontent.com/62424178/77156030-d0e0ec80-6a9e-11ea-97a4-944cd320830c.png)

version TakaAntiCheat:
![image](https://user-images.githubusercontent.com/62424178/77156077-ec4bf780-6a9e-11ea-8634-02737778b723.png)

**Comment by dani02021** [comment]
Thank you for the report, fixed, the update will be posted after a few hours.
